# 欢迎使用Jekyll！
#
# 这个配置文件用于设置影响整个网站的参数，这些值通常只需要在设置一次后很少编辑。
# 由于技术原因，在使用 `jekyll serve` 时，该文件不会自动重新加载。
# 如果你修改了这个文件，请重新启动服务器进程。

# 网站设置
locale                   : "en-US"
title                    : "个人主页"
title_separator          : "-"
name                     : &name "肖雄"
description              : &description "personal description"
url                      : https://a-strong-python.github.io # 网站的基本主机名和协议，例如 "https://mmistakes.github.io"
baseurl                  : "" # 网站的子路径，例如 "/blog"
repository               : "a-strong-python/a-strong-python.github.io"
teaser                   :  # 首页缩略图，放置在 /images/ 目录下，例如 "500x300.png"
breadcrumbs              : false # true, false (默认)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # 如果启用，会在摘要中添加 "阅读更多" 的链接
talkmap_link             : false # 将其更改为 true 以在演讲页面上添加到 talkmap 的链接
comments:
  provider               : # false (默认), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 ，例如：meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (默认)
    colorscheme          : # "light" (默认), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (默认), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path                   : # 空白 (默认) 使用 feed.xml

# SEO 相关
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# 社交分享
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter 默认站点图像
# 用于指定社交资料
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person 或 Organization（默认为 Person）
  name                   : # 如果用户或组织名称与网站名称不同
  links: # 社交媒体资料的链接数组

# 分析
analytics:
  provider               :  "google-universal" # false (默认), "google", "google-universal", "custom"
  google:
    tracking_id          :

# 网站作者
author:
  name             : "肖雄"
  avatar           : "个人照片.jpg"
  bio              : "Coding is a valuable thing！"
  location         : "湖北荆州"
  email            : "1784036791@qq.com"
  github           : "a-strong-python"
  gitee            : "a-strong-python"
  csdn             : "weixin_46227276"
  aistudio         : "1870692"
  openi            : "xiaoxiong"


# 读取文件
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# 转换
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown 处理
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# 集合
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# 默认值
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# 输出
permalink: /:categories/:title/
# paginate: 5 # 显示的帖子数量
# paginate_path: /page:num/
timezone: America/Los_Angeles # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# 插件
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# 模仿 GitHub Pages 使用 --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# 存档
#  类型
#  - 使用 Liquid 构建的与 GitHub Pages 兼容的归档页面 ~> type: liquid（默认）
#  - 使用 Jekyll Archives 插件的归档页面 ~> type: jekyll-archives
#  路径（示例）
#  - 在使用 Liquid 方法时，应在路径上存在归档页面，或者你可以
#    期望找到破碎的链接（尤其是在启用面包屑的情况下）
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# HTML 压缩
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
